version: '3.8'
name: MDS_Tehnicki_zadatak


services:


  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  

  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    container_name: django
    depends_on:
      postgres:
        condition: service_healthy # Django waits for PostgreSQL
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-7byic=x**rvi4^a(%##%4_k*8+q^x3tql+!sz#i$tp0h5!k$s&
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/stock_db

    ports:
      - '8000:8000'
      
    volumes:
      - ./MDS_Tehnicki_zadatak:/stocks/MDS_Tehnicki_zadatak
    # command: ["/stocks/wait_for_db.sh", "python", "manage.py", "migrate"]
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
 
  
volumes:
  postgres_data:
  pgadmin_data: